/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgRouteRouteImport } from './routes/org/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OrgVerifyEmailRouteImport } from './routes/org/verify-email'
import { Route as OrgRegisterRouteImport } from './routes/org/register'
import { Route as OrgLoginRouteImport } from './routes/org/login'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardProjectsProjectIdIndexRouteImport } from './routes/dashboard/projects/$projectId/index'
import { Route as DashboardProjectsProjectIdEditIndexRouteImport } from './routes/dashboard/projects/$projectId/edit/index'
import { Route as DashboardProjectsProjectIdMemberMemberIdIndexRouteImport } from './routes/dashboard/projects/$projectId/member/$memberId/index'

const OrgRouteRoute = OrgRouteRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const OrgVerifyEmailRoute = OrgVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgRegisterRoute = OrgRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgLoginRoute = OrgLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OrgRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsProjectIdIndexRoute =
  DashboardProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectsProjectIdEditIndexRoute =
  DashboardProjectsProjectIdEditIndexRouteImport.update({
    id: '/projects/$projectId/edit/',
    path: '/projects/$projectId/edit/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectsProjectIdMemberMemberIdIndexRoute =
  DashboardProjectsProjectIdMemberMemberIdIndexRouteImport.update({
    id: '/projects/$projectId/member/$memberId/',
    path: '/projects/$projectId/member/$memberId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/org': typeof OrgRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/org/login': typeof OrgLoginRoute
  '/org/register': typeof OrgRegisterRoute
  '/org/verify-email': typeof OrgVerifyEmailRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/dashboard/projects/$projectId/edit/': typeof DashboardProjectsProjectIdEditIndexRoute
  '/dashboard/projects/$projectId/member/$memberId/': typeof DashboardProjectsProjectIdMemberMemberIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/org': typeof OrgRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/org/login': typeof OrgLoginRoute
  '/org/register': typeof OrgRegisterRoute
  '/org/verify-email': typeof OrgVerifyEmailRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdIndexRoute
  '/dashboard/projects/$projectId/edit': typeof DashboardProjectsProjectIdEditIndexRoute
  '/dashboard/projects/$projectId/member/$memberId': typeof DashboardProjectsProjectIdMemberMemberIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/org': typeof OrgRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/org/login': typeof OrgLoginRoute
  '/org/register': typeof OrgRegisterRoute
  '/org/verify-email': typeof OrgVerifyEmailRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/dashboard/projects/$projectId/edit/': typeof DashboardProjectsProjectIdEditIndexRoute
  '/dashboard/projects/$projectId/member/$memberId/': typeof DashboardProjectsProjectIdMemberMemberIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/org'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/org/login'
    | '/org/register'
    | '/org/verify-email'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/projects/'
    | '/dashboard/settings/'
    | '/dashboard/projects/$projectId/'
    | '/dashboard/projects/$projectId/edit/'
    | '/dashboard/projects/$projectId/member/$memberId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/org'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/org/login'
    | '/org/register'
    | '/org/verify-email'
    | '/dashboard'
    | '/docs'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/$projectId/edit'
    | '/dashboard/projects/$projectId/member/$memberId'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/dashboard'
    | '/org'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/verify-email'
    | '/org/login'
    | '/org/register'
    | '/org/verify-email'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/projects/'
    | '/dashboard/settings/'
    | '/dashboard/projects/$projectId/'
    | '/dashboard/projects/$projectId/edit/'
    | '/dashboard/projects/$projectId/member/$memberId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  OrgRouteRoute: typeof OrgRouteRouteWithChildren
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/org/verify-email': {
      id: '/org/verify-email'
      path: '/verify-email'
      fullPath: '/org/verify-email'
      preLoaderRoute: typeof OrgVerifyEmailRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/register': {
      id: '/org/register'
      path: '/register'
      fullPath: '/org/register'
      preLoaderRoute: typeof OrgRegisterRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/login': {
      id: '/org/login'
      path: '/login'
      fullPath: '/org/login'
      preLoaderRoute: typeof OrgLoginRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/$projectId/': {
      id: '/dashboard/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/$projectId/edit/': {
      id: '/dashboard/projects/$projectId/edit/'
      path: '/projects/$projectId/edit'
      fullPath: '/dashboard/projects/$projectId/edit/'
      preLoaderRoute: typeof DashboardProjectsProjectIdEditIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/$projectId/member/$memberId/': {
      id: '/dashboard/projects/$projectId/member/$memberId/'
      path: '/projects/$projectId/member/$memberId'
      fullPath: '/dashboard/projects/$projectId/member/$memberId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdMemberMemberIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardProjectsProjectIdIndexRoute: typeof DashboardProjectsProjectIdIndexRoute
  DashboardProjectsProjectIdEditIndexRoute: typeof DashboardProjectsProjectIdEditIndexRoute
  DashboardProjectsProjectIdMemberMemberIdIndexRoute: typeof DashboardProjectsProjectIdMemberMemberIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardProjectsProjectIdIndexRoute: DashboardProjectsProjectIdIndexRoute,
  DashboardProjectsProjectIdEditIndexRoute:
    DashboardProjectsProjectIdEditIndexRoute,
  DashboardProjectsProjectIdMemberMemberIdIndexRoute:
    DashboardProjectsProjectIdMemberMemberIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface OrgRouteRouteChildren {
  OrgLoginRoute: typeof OrgLoginRoute
  OrgRegisterRoute: typeof OrgRegisterRoute
  OrgVerifyEmailRoute: typeof OrgVerifyEmailRoute
}

const OrgRouteRouteChildren: OrgRouteRouteChildren = {
  OrgLoginRoute: OrgLoginRoute,
  OrgRegisterRoute: OrgRegisterRoute,
  OrgVerifyEmailRoute: OrgVerifyEmailRoute,
}

const OrgRouteRouteWithChildren = OrgRouteRoute._addFileChildren(
  OrgRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OrgRouteRoute: OrgRouteRouteWithChildren,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
